### ISSUE TITLE
Error Conflicts with diverts-etc++defaults++tor

### ISSUE THREAD

**Issue by hitamjahat** [Whonix/anon-gw-anonymizer-config#1]
hi when i tried install this on debian i got an error "conflict with diverts-etc++defaults++tor"
how can i fix this?

**Comment by adrelanos** [comment]
https://www.whonix.org/wiki/Reporting_Bugs#Reporting_Guidelines

https://www.whonix.org/wiki/Reporting_Bugs#Out_of_Scope_Issues?
